title: Your awesome title
author: GitHub User
email: your-email@domain.com
introduction: This is a proper introduction of your site.
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
twitter_username: jekyllrb
github_username:  jekyll
google_plus_username: +jekyll
company_image: /assets/companyIcon.svg
windows_icon: > # Favicon location for .ico files foe microsoft browsers
icon: /assets/companyIcon.svg #Favicon for all other browsers

# Build settings
markdown: kramdown
theme: grapevine
exclude:
  - Gemfile
  - Gemfile.lock